stages:
  - publish

publish:
  stage: publish
  script:
    # Install dependencies and build app
    - npm install
    - npm run build
    # needed for npm version to work
    - git add . && git commit
    # Bump version
    - npm version patch
    # Auth and publish to NPM
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish
