stages:
  - publish

publish:
  stage: publish
  script:
    # Install dependencies and build app
    - npm install
    - npm run build
    # Bump version
    - npm install -g npm-bump
    - npm-bump patch
    # Auth and publish to NPM
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish
